# Generated by Django 4.1.1 on 2023-02-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coagulaciones',
            fields=[
                ('nss', models.FloatField(primary_key=True, serialize=False, unique=True)),
                ('folio_orden', models.FloatField()),
                ('determinacion', models.CharField(max_length=100)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_normal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drogas_terapeuticas',
            fields=[
                ('nss', models.FloatField(primary_key=True, serialize=False, unique=True)),
                ('folio_orden', models.FloatField()),
                ('determinacion', models.CharField(max_length=100)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_normal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hematologia',
            fields=[
                ('nss', models.FloatField(primary_key=True, serialize=False, unique=True)),
                ('folio_orden', models.FloatField()),
                ('determinacion', models.CharField(max_length=100)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_normal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inmuno_infecto',
            fields=[
                ('nss', models.FloatField(primary_key=True, serialize=False, unique=True)),
                ('folio_orden', models.FloatField()),
                ('determinacion', models.CharField(max_length=100)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_normal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inmunologia',
            fields=[
                ('nss', models.FloatField(primary_key=True, serialize=False, unique=True)),
                ('folio_orden', models.FloatField()),
                ('determinacion', models.CharField(max_length=100)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_normal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('nss', models.FloatField(primary_key=True, serialize=False, unique=True)),
                ('folio_orden', models.FloatField(unique=True)),
                ('fecha_orden', models.DateField(blank=True, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('servicio_solicita', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicina_nuclear',
            fields=[
                ('nss', models.FloatField(primary_key=True, serialize=False, unique=True)),
                ('folio_orden', models.FloatField()),
                ('determinacion', models.CharField(max_length=100)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_normal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nota_egreso',
            fields=[
                ('nss', models.FloatField(primary_key=True, serialize=False, unique=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_egreso', models.DateField()),
                ('especialidad_egreso', models.CharField(blank=True, max_length=500, null=True)),
                ('motivo_egreso', models.CharField(blank=True, max_length=500, null=True)),
                ('envio', models.CharField(blank=True, max_length=250, null=True)),
                ('diagnostico_ingreso', models.CharField(blank=True, max_length=800, null=True)),
                ('diagnostico_egreso', models.CharField(blank=True, max_length=800, null=True)),
                ('resumen_evolucion', models.TextField(blank=True, null=True)),
                ('problemas_pendientes', models.TextField(blank=True, null=True)),
                ('plan_tratamiento', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('factores_riesgo', models.CharField(blank=True, max_length=500, null=True)),
                ('pronostico', models.CharField(blank=True, max_length=500, null=True)),
                ('diagnostico_defuncion', models.CharField(blank=True, max_length=500, null=True)),
                ('estado_salud', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('talla', models.FloatField(blank=True, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('frec_respiratoria', models.FloatField(blank=True, null=True)),
                ('frec_cardiaca', models.FloatField(blank=True, null=True)),
                ('pres_arterial', models.CharField(blank=True, max_length=10, null=True)),
                ('imc', models.FloatField(blank=True, null=True)),
                ('saturacion', models.FloatField(blank=True, null=True)),
                ('glc_capilar', models.FloatField(blank=True, null=True)),
                ('diagnostico_final', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nota_inicial',
            fields=[
                ('nss', models.FloatField(primary_key=True, serialize=False, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('genero', models.CharField(blank=True, max_length=5, null=True)),
                ('especialidad_ingreso', models.CharField(blank=True, max_length=500, null=True)),
                ('motivo_inter', models.CharField(blank=True, max_length=250, null=True)),
                ('interrogatorio', models.TextField(blank=True, null=True)),
                ('dx', models.CharField(blank=True, max_length=500, null=True)),
                ('plan_tratamiento', models.TextField(blank=True, null=True)),
                ('pronostico', models.CharField(blank=True, max_length=1000, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('estado_salud', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('talla', models.FloatField(blank=True, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('frec_respiratoria', models.FloatField(blank=True, null=True)),
                ('frec_cardiaca', models.FloatField(blank=True, null=True)),
                ('pres_arterial', models.CharField(blank=True, max_length=10, null=True)),
                ('imc', models.FloatField(blank=True, null=True)),
                ('saturacion', models.FloatField(blank=True, null=True)),
                ('glc_capilar', models.FloatField(blank=True, null=True)),
                ('diagnostico_inicial', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nss', models.FloatField(primary_key=True, serialize=False, unique=True)),
                ('nombre_paciente', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pruebas_especiales',
            fields=[
                ('nss', models.FloatField(primary_key=True, serialize=False, unique=True)),
                ('folio_orden', models.FloatField()),
                ('determinacion', models.CharField(max_length=100)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_normal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quimica_clinica',
            fields=[
                ('nss', models.FloatField(primary_key=True, serialize=False, unique=True)),
                ('folio_orden', models.FloatField()),
                ('determinacion', models.CharField(max_length=100)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_normal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='quimica_clinica',
            constraint=models.UniqueConstraint(fields=('nss', 'folio_orden', 'determinacion'), name='unique_migration_Quimica_clinica'),
        ),
        migrations.AddConstraint(
            model_name='pruebas_especiales',
            constraint=models.UniqueConstraint(fields=('nss', 'folio_orden', 'determinacion'), name='unique_migration_Pruebas_especiales'),
        ),
        migrations.AddConstraint(
            model_name='nota_inicial',
            constraint=models.UniqueConstraint(fields=('nss', 'fecha_ingreso'), name='unique_migration_Nota_inicial'),
        ),
        migrations.AddConstraint(
            model_name='nota_egreso',
            constraint=models.UniqueConstraint(fields=('nss', 'fecha_egreso'), name='unique_migration_Nota_egreso'),
        ),
        migrations.AddConstraint(
            model_name='medicina_nuclear',
            constraint=models.UniqueConstraint(fields=('nss', 'folio_orden', 'determinacion'), name='unique_migration_Medicina_nuclear'),
        ),
        migrations.AddConstraint(
            model_name='laboratorio',
            constraint=models.UniqueConstraint(fields=('nss', 'folio_orden'), name='unique_migration_host_combination'),
        ),
        migrations.AddConstraint(
            model_name='inmunologia',
            constraint=models.UniqueConstraint(fields=('nss', 'folio_orden', 'determinacion'), name='unique_migration_Inmunologia'),
        ),
        migrations.AddConstraint(
            model_name='inmuno_infecto',
            constraint=models.UniqueConstraint(fields=('nss', 'folio_orden', 'determinacion'), name='unique_migration_Inmuno_infecto'),
        ),
        migrations.AddConstraint(
            model_name='hematologia',
            constraint=models.UniqueConstraint(fields=('nss', 'folio_orden', 'determinacion'), name='unique_migration_Hematologia'),
        ),
        migrations.AddConstraint(
            model_name='drogas_terapeuticas',
            constraint=models.UniqueConstraint(fields=('nss', 'folio_orden', 'determinacion'), name='unique_migration_Drogas_terapeuticas'),
        ),
        migrations.AddConstraint(
            model_name='coagulaciones',
            constraint=models.UniqueConstraint(fields=('nss', 'folio_orden', 'determinacion'), name='unique_migration_Coagulaciones'),
        ),
    ]
